_name_or_path:
    value: roberta-base
_wandb:
    value:
        cli_version: 0.22.2
        e:
            ekwwdk85khkh9nvvt2cy4y57xp7k4rox:
                args:
                    - --dataset_name=dair-ai/emotion
                    - --do_eval=True
                    - --do_predict=True
                    - --do_train=True
                    - --eval_strategy=epoch
                    - --label_column_name=label
                    - --learning_rate=2e-05
                    - --load_best_model_at_end=True
                    - --max_seq_length=128
                    - --metric_for_best_model=accuracy
                    - --metric_name=accuracy
                    - --model_name_or_path=roberta-base
                    - --num_train_epochs=5
                    - --output_dir=./prompt_tuning_soft_outputs
                    - --peft_method=prompt_tuning
                    - --per_device_train_batch_size=64
                    - --prompt_tuning_num_virtual_tokens=16
                    - --report_to=wandb
                    - --save_strategy=epoch
                    - --save_total_limit=2
                    - --seed=23
                    - --shuffle_train_dataset=True
                    - --text_column_name=text
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "107321753600"
                        used: "13965533184"
                email: caoduy73@gmail.com
                executable: /home/e/e0969050/dsa4213/dsa4213-assignment-3/.venv/bin/python
                git:
                    commit: e9625bbb1d86481470e385000b5086911f1432c7
                    remote: git@github.com:ncduy0303/dsa4213-assignment-3.git
                gpu: NVIDIA H100 NVL
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-3cfb419b-0f7b-b3a1-b6ee-89a37bda793f
                host: xgpi5
                memory:
                    total: "1081863548928"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.39
                program: /home/e/e0969050/dsa4213/dsa4213-assignment-3/train.py
                python: CPython 3.13.7
                root: /home/e/e0969050/dsa4213/dsa4213-assignment-3
                slurm:
                    cluster_name: soc
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "2"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: allusers
                    job_cpus_per_node: "2"
                    job_end_time: "1760628051"
                    job_gid: "140"
                    job_gpus: "1"
                    job_id: "191269"
                    job_name: prompt_tuning_soft
                    job_nodelist: xgpi5
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1760617251"
                    job_uid: "48066"
                    job_user: e0969050
                    jobid: "191269"
                    localid: "0"
                    mem_per_cpu: "4096"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: xgpi5
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /home/e/e0969050/dsa4213/dsa4213-assignment-3
                    submit_host: xlogin1
                    task_pid: "1218604"
                    tasks_per_node: "1"
                    topology_addr: xgpi5
                    topology_addr_pattern: node
                startedAt: "2025-10-16T12:24:19.428792Z"
                writerId: ekwwdk85khkh9nvvt2cy4y57xp7k4rox
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
            "3":
                - 7
                - 14
                - 19
                - 62
                - 66
            "4": 3.13.7
            "5": 0.22.2
            "6": 4.57.0
            "9":
                "1": transformers_trainer
            "12": 0.22.2
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - RobertaForMaskedLM
attention_probs_dropout_prob:
    value: 0.1
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: 0
chunk_size_feed_forward:
    value: 0
classifier_dropout:
    value: null
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_name:
    value: dair-ai/emotion
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: true
do_sample:
    value: false
do_train:
    value: true
dtype:
    value: float32
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 2
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: epoch
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: text-classification
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: true
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: gelu
hidden_dropout_prob:
    value: 0.1
hidden_size:
    value: 768
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": "0"
        "1": "1"
        "2": "2"
        "3": "3"
        "4": "4"
        "5": "5"
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: "no"
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 3072
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_column_name:
    value: label
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        "0": 0
        "1": 1
        "2": 2
        "3": 3
        "4": 4
        "5": 5
layer_norm_eps:
    value: 1e-05
learning_rate:
    value: 2e-05
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ./prompt_tuning_soft_outputs/runs/Oct16_20-24-08_xgpi5
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 500
logging_strategy:
    value: steps
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 514
max_seq_length:
    value: 128
max_steps:
    value: -1
metric_for_best_model:
    value: accuracy
metric_name:
    value: accuracy
min_length:
    value: 0
model/num_parameters:
    value: 125245452
model_name_or_path:
    value: roberta-base
model_type:
    value: roberta
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 12
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 12
num_return_sequences:
    value: 1
num_train_epochs:
    value: 5
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./prompt_tuning_soft_outputs
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 1
parallelism_config:
    value: null
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: roberta-base
            inference_mode: false
            modules_to_save:
                - classifier
                - score
                - classifier
                - score
            num_attention_heads: 12
            num_layers: 12
            num_transformer_submodules: 1
            num_virtual_tokens: 16
            peft_type: PROMPT_TUNING
            prompt_tuning_init: RANDOM
            prompt_tuning_init_text: null
            revision: null
            task_type: SEQ_CLS
            token_dim: 768
            tokenizer_kwargs: null
            tokenizer_name_or_path: null
peft_method:
    value: prompt_tuning
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 64
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
position_embedding_type:
    value: absolute
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: single_label_classification
project:
    value: huggingface
prompt_tuning_num_virtual_tokens:
    value: 16
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value: wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: null
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 500
save_strategy:
    value: epoch
save_total_limit:
    value: 2
seed:
    value: 23
sep_token_id:
    value: null
shuffle_train_dataset:
    value: true
skip_memory_metrics:
    value: true
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
text_column_name:
    value: text
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
trackio_space_id:
    value: trackio
transformers_version:
    value: 4.57.0
type_vocab_size:
    value: 1
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 50265
warmup_ratio:
    value: 0
warmup_steps:
    value: 0
weight_decay:
    value: 0
