wandb_version: 1

dataset_name:
  value: dair-ai/emotion
do_eval:
  value: true
do_predict:
  value: true
do_train:
  value: true
eval_strategy:
  value: epoch
label_column_name:
  value: label
learning_rate:
  value: 0.002
load_best_model_at_end:
  value: true
lora_alpha:
  value: 16
lora_bias:
  value: none
lora_dropout:
  value: 0.1
lora_r:
  value: 8
lora_target_modules:
  value: query,value
max_seq_length:
  value: 128
metric_for_best_model:
  value: accuracy
metric_name:
  value: accuracy
model_name_or_path:
  value: roberta-base
num_train_epochs:
  value: 5
output_dir:
  value: ./lora_outputs
peft_method:
  value: lora
per_device_train_batch_size:
  value: 64
report_to:
  value: wandb
save_strategy:
  value: epoch
save_total_limit:
  value: 2
seed:
  value: 23
shuffle_train_dataset:
  value: true
text_column_name:
  value: text
