wandb_version: 1

dataset_name:
  value: dair-ai/emotion
do_eval:
  value: true
do_predict:
  value: true
do_train:
  value: true
eval_strategy:
  value: epoch
label_column_name:
  value: label
learning_rate:
  value: 2.0e-05
load_best_model_at_end:
  value: true
max_seq_length:
  value: 128
metric_for_best_model:
  value: accuracy
metric_name:
  value: accuracy
model_name_or_path:
  value: roberta-base
num_train_epochs:
  value: 5
output_dir:
  value: ./prompt_tuning_soft_outputs
peft_method:
  value: prompt_tuning
per_device_train_batch_size:
  value: 64
prompt_tuning_init_text:
  value: 'determine the emotion expressed in the text: '
report_to:
  value: wandb
save_strategy:
  value: epoch
save_total_limit:
  value: 2
seed:
  value: 23
shuffle_train_dataset:
  value: true
text_column_name:
  value: text
